# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout current repository to Master branch
        uses: actions/checkout@v1
      # Test displaying COMMIT_ID using env variable : COMMIT_ID
      - name: Test env 
        env:
          COMMIT_ID: ${{GITHUB_SHA}}
        run: echo "commit ID =>$COMMIT_ID"
      - name: Run online scriopt
#         env:
#           COMMIT_ID: "1234"
        run: env
