# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Run env to display available env
        run: env

      # Test displaying COMMIT_ID using env variable : COMMIT_ID
      - name:  displaying GITHUB_SHA using env variable 
        env:
            COMMIT_ID: $GITHUB_SHA
        run: echo "commit ID => $COMMIT_ID "
        
